"""Pure normalization functions: map a raw metric value onto a 0-100 score.

Every function here is total (defined for any Decimal input, including
extreme outliers) and deterministic — no metric-availability logic
lives here, only "given a number, what score does it imply." Callers
are responsible for only calling these once they know the underlying
metric was actually calculated.
"""

from decimal import Decimal

from app.scoring.thresholds import (
    CURRENT_RATIO_DANGER,
    CURRENT_RATIO_DANGER_SCORE,
    CURRENT_RATIO_EXCESSIVE,
    CURRENT_RATIO_EXCESSIVE_SCORE,
    CURRENT_RATIO_IDEAL_HIGH,
    CURRENT_RATIO_IDEAL_LOW,
    LinearBand,
)

_ZERO = Decimal(0)
_HUNDRED = Decimal(100)


def normalize_linear_higher_is_better(value: Decimal, band: LinearBand) -> Decimal:
    """Score rises linearly from 0 at `band.floor` to 100 at `band.target`,
    clamped outside that range."""
    if value <= band.floor:
        return _ZERO
    if value >= band.target:
        return _HUNDRED
    return (value - band.floor) / (band.target - band.floor) * _HUNDRED


def normalize_linear_lower_is_better(value: Decimal, band: LinearBand) -> Decimal:
    """Score falls linearly from 100 at `band.floor` to 0 at `band.target`,
    clamped outside that range."""
    if value <= band.floor:
        return _HUNDRED
    if value >= band.target:
        return _ZERO
    return (band.target - value) / (band.target - band.floor) * _HUNDRED


def normalize_current_ratio(value: Decimal) -> Decimal:
    """Current ratio's "sweet spot" shape.

    - value <= 0                                  -> 0 (defensive floor)
    - 0 < value < danger (1.0)                     -> ramps 0 -> 60
    - danger (1.0) <= value < ideal_low (1.5)      -> ramps 60 -> 100
    - ideal_low (1.5) <= value <= ideal_high (3.0) -> 100 (healthy plateau)
    - ideal_high (3.0) < value < excessive (6.0)   -> eases 100 -> 70
    - value >= excessive (6.0)                     -> flat at 70

    Very low liquidity is a genuine danger; very high liquidity means
    idle capital, which is inefficient but not itself risky — so it is
    never scored as harshly as the low-liquidity danger zone.
    """
    if value <= _ZERO:
        return _ZERO
    if value < CURRENT_RATIO_DANGER:
        return value / CURRENT_RATIO_DANGER * CURRENT_RATIO_DANGER_SCORE
    if value < CURRENT_RATIO_IDEAL_LOW:
        span = CURRENT_RATIO_IDEAL_LOW - CURRENT_RATIO_DANGER
        progress = value - CURRENT_RATIO_DANGER
        return CURRENT_RATIO_DANGER_SCORE + (progress / span) * (_HUNDRED - CURRENT_RATIO_DANGER_SCORE)
    if value <= CURRENT_RATIO_IDEAL_HIGH:
        return _HUNDRED
    if value < CURRENT_RATIO_EXCESSIVE:
        span = CURRENT_RATIO_EXCESSIVE - CURRENT_RATIO_IDEAL_HIGH
        progress = value - CURRENT_RATIO_IDEAL_HIGH
        return _HUNDRED - (progress / span) * (_HUNDRED - CURRENT_RATIO_EXCESSIVE_SCORE)
    return CURRENT_RATIO_EXCESSIVE_SCORE


def explain_score(display_name: str, score: Decimal) -> str:
    """A deterministic, template-based explanation of a 0-100 score.

    Never generated by an LLM — the tiers and wording are fixed here.
    """
    if score >= 80:
        tier = "well above the strong-performance threshold"
    elif score >= 60:
        tier = "above the average-performance threshold"
    elif score >= 40:
        tier = "roughly in line with typical performance"
    elif score >= 20:
        tier = "below the average-performance threshold"
    else:
        tier = "well below the minimum acceptable threshold"
    return f"{display_name} is {tier}"
