import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
page.on('console', msg => console.log('CONSOLE:', msg.text()));
page.on('requestfailed', req => console.log('FAILED:', req.url(), req.failure()?.errorText));
page.on('response', res => { if (res.url().includes('indices')) console.log('RESPONSE', res.status(), res.url()); });
await page.goto('http://localhost:5173/', { waitUntil: 'networkidle' });
await page.getByRole('button', { name: /^sign up$/i }).first().click();
const email = `check_final2_${Date.now()}@example.com`;
await page.getByLabel(/email/i).fill(email);
await page.getByLabel(/^password/i).fill('TestPassword123!');
await page.getByRole('main').getByRole('button', { name: /^sign up$/i }).click();
await page.waitForTimeout(1200);
await page.getByRole('button', { name: /^intelligence$/i }).click();
await page.waitForTimeout(3000);
console.log('done');
await browser.close();
