import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
page.on('request', req => { if (req.url().includes('/api/v1/market')) console.log('REQ', req.method(), req.url()); });
page.on('response', async res => { if (res.url().includes('/api/v1/market')) console.log('RES', res.status(), res.url()); });
page.on('pageerror', err => console.log('PAGEERROR', err.message));
await page.goto('http://localhost:5173/', { waitUntil: 'networkidle' });
await page.getByRole('button', { name: /^sign up$/i }).first().click();
const email = `check_final3_${Date.now()}@example.com`;
await page.getByLabel(/email/i).fill(email);
await page.getByLabel(/^password/i).fill('TestPassword123!');
await page.getByRole('main').getByRole('button', { name: /^sign up$/i }).click();
await page.waitForTimeout(1200);
await page.getByRole('button', { name: /^intelligence$/i }).click();
await page.waitForTimeout(3000);
console.log('done');
await browser.close();
