"""Explanation engine (spec section 24) -- turns the actual computed
feature row + regime + analog stats into plain-language positive/negative
drivers. Every driver string here is gated on a real threshold applied to
a real feature value; nothing is generated by an LLM or invented.
"""

from dataclasses import dataclass

import pandas as pd

from app.forecasting.ml.analog import AnalogHorizonStats
from app.forecasting.ml.regime import Regime


@dataclass(frozen=True)
class ForecastDrivers:
    positive_drivers: list[str]
    negative_drivers: list[str]


def explain_forecast(*, features: pd.Series, regime: Regime, analog_stats: AnalogHorizonStats | None) -> ForecastDrivers:
    positive: list[str] = []
    negative: list[str] = []

    def get(name: str) -> float | None:
        value = features.get(name)
        return None if value is None or pd.isna(value) else float(value)

    return_30d = get("return_30d")
    if return_30d is not None:
        if return_30d > 0.08:
            positive.append("Strong medium-term momentum (30-day return above 8%)")
        elif return_30d < -0.08:
            negative.append("Weak medium-term momentum (30-day return below -8%)")

    rel_strength = get("relative_strength_30d")
    if rel_strength is not None:
        if rel_strength > 0.03:
            positive.append("Outperforming the broader market over the last month")
        elif rel_strength < -0.03:
            negative.append("Underperforming the broader market over the last month")

    price_vs_sma50 = get("price_vs_sma50")
    if price_vs_sma50 is not None:
        if 0 < price_vs_sma50 <= 0.10:
            positive.append("Trading above its 50-day average")
        elif price_vs_sma50 > 0.15:
            negative.append("Price significantly above its 50-day average (stretched)")
        elif price_vs_sma50 < -0.05:
            negative.append("Trading below its 50-day average")

    rsi = get("rsi_14")
    if rsi is not None:
        if rsi >= 75:
            negative.append("RSI indicates overbought conditions")
        elif rsi <= 30:
            negative.append("RSI indicates oversold conditions (elevated reversal risk)")

    volatility = get("volatility_20d")
    if volatility is not None and volatility > 0.40:
        negative.append("Elevated short-term volatility")

    volume_ratio = get("volume_ratio_20d")
    if volume_ratio is not None and volume_ratio > 1.5:
        positive.append("Above-average trading volume recently")

    if regime == Regime.TRENDING_UP:
        positive.append("Price structure is in a confirmed uptrend")
    elif regime == Regime.TRENDING_DOWN:
        negative.append("Price structure is in a confirmed downtrend")
    elif regime == Regime.OVEREXTENDED:
        negative.append("Recent rally is statistically unusual (overextended regime)")
    elif regime == Regime.BREAKOUT:
        positive.append("Price broke out to a new 52-week high on rising volume/momentum")
    elif regime == Regime.MEAN_REVERSION:
        negative.append("Momentum extremes historically precede mean reversion")
    elif regime == Regime.HIGH_VOLATILITY:
        negative.append("Regime is high-volatility, widening the plausible outcome range")

    if analog_stats is not None:
        if analog_stats.is_reliable and analog_stats.median_return is not None:
            if analog_stats.median_return < -0.01 and analog_stats.positive_rate is not None and analog_stats.positive_rate < 0.45:
                negative.append(
                    f"Historical analogs (n={analog_stats.sample_size}) show reversal risk from similar setups"
                )
            elif analog_stats.median_return > 0.01 and analog_stats.positive_rate is not None and analog_stats.positive_rate > 0.55:
                positive.append(
                    f"Historical analogs (n={analog_stats.sample_size}) were positive from similar setups"
                )
        else:
            negative.append("Historical analog sample is too small to be reliable")

    return ForecastDrivers(positive_drivers=positive, negative_drivers=negative)
